# Generated by Django 5.0.4 on 2024-10-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_actionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeystrokeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=10)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("down", "KeyDown"), ("up", "KeyUp")], max_length=10
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Keystroke Log",
                "verbose_name_plural": "Keystroke Logs",
            },
        ),
        migrations.CreateModel(
            name="MouseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("move", "Move"),
                            ("click", "Click"),
                            ("scroll", "Scroll"),
                        ],
                        max_length=50,
                    ),
                ),
                ("x_coordinate", models.FloatField()),
                ("y_coordinate", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Mouse Log",
                "verbose_name_plural": "Mouse Logs",
            },
        ),
        migrations.CreateModel(
            name="WebActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_web_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
