# Generated by Django 5.0.4 on 2024-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keystrokelog",
            name="action",
            field=models.CharField(
                choices=[("press", "Press"), ("release", "Release")],
                default="key_press",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="keystrokelog",
            name="rhythm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouseactionlog",
            name="button",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right"), ("middle", "Middle")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mouseactionlog",
            name="delta",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mouseactionlog",
            name="action",
            field=models.CharField(
                choices=[("move", "Move"), ("click", "Click"), ("scroll", "Scroll")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mouseactionlog",
            name="coordinates",
            field=models.CharField(max_length=50),
        ),
    ]
