# Generated by Django 5.0.4 on 2025-01-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0002_keystrokelog_action_keystrokelog_rhythm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackspaceCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="keystrokelog",
            name="dwell_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keystrokelog",
            name="flight_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keystrokelog",
            name="up_down_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouseactionlog",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouseactionlog",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
